import { FileCode2, Hash, Link2, ShieldCheck } from "lucide-react";
import type { RcaResult } from "@/types";
import { EvidenceMetadataRow } from "@/components/job/EvidenceMetadataRow";
import { interpretConfidence } from "@/lib/rcaConfidence";
import { ConfidenceProgressBar } from "./ConfidenceProgressBar";
import { splitRootCausePath } from "@/lib/utils";
import { cn } from "@/lib/utils";

function LayerLabelPills({
  primary,
  secondary,
}: {
  primary: string;
  secondary: string;
}) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <span className="inline-flex items-center rounded-full border border-violet-400/35 bg-violet-500/[0.14] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-violet-100/95 shadow-[0_0_20px_-12px_rgba(139,92,246,0.8)]">
        {primary}
      </span>
      <span
        className="inline-flex items-center rounded-full border border-white/[0.1] bg-white/[0.04] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400"
        title="Authoritative ranked output — not generated by the assistive model"
      >
        {secondary}
      </span>
    </div>
  );
}

interface RcaResultCardProps {
  rca: RcaResult;
  className?: string;
  /** When false, omit the in-card title — use with a page-level “Deterministic Root Cause” heading */
  showHeading?: boolean;
}

function RootCausePathBlock({ path }: { path: string }) {
  const trimmed = path.trim();
  if (!trimmed) {
    return (
      <div className="rounded-xl border border-dashed border-amber-500/25 bg-gradient-to-br from-amber-500/[0.06] to-[#060a12]/90 px-4 py-4 shadow-inner ring-1 ring-inset ring-amber-500/10">
        <div className="flex gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-slate-600/40 bg-black/[0.88]">
            <FileCode2 className="h-5 w-5 text-slate-500" strokeWidth={1.75} />
          </div>
          <div className="min-w-0">
            <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-amber-200/80">
              No ranked path yet
            </p>
            <p className="mt-1 text-sm leading-relaxed text-slate-400">
              The RCA response did not include a file path — correlation may still be
              running, or the candidate set was empty.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const { segments, lineRange, isStructured } = splitRootCausePath(trimmed);

  if (!isStructured || segments.length === 0) {
    return (
      <div className="overflow-hidden rounded-xl border border-slate-700/60 bg-[#060a12] shadow-inner ring-1 ring-inset ring-white/[0.04]">
        <div className="flex items-center gap-2 border-b border-slate-700/50 px-3 py-2">
          <FileCode2 className="h-3.5 w-3.5 text-slate-500" strokeWidth={2} />
          <span className="font-mono text-[10px] font-semibold uppercase tracking-wider text-slate-500">
            Ranked path (raw)
          </span>
        </div>
        <pre className="overflow-x-auto px-4 py-3.5 font-mono text-[14px] leading-relaxed text-slate-200 [tab-size:2]">
          <code className="break-all">{trimmed}</code>
        </pre>
      </div>
    );
  }

  const dir = segments.slice(0, -1);
  const file = segments[segments.length - 1]!;

  return (
    <div className="overflow-x-auto rounded-xl border border-emerald-400/25 bg-[#060a12] shadow-[0_0_40px_-20px_rgba(16,185,129,0.35)] ring-1 ring-inset ring-emerald-500/15">
      <div className="flex items-center gap-2 border-b border-emerald-500/20 bg-emerald-500/[0.09] px-4 py-3">
        <FileCode2 className="h-4 w-4 text-emerald-400" strokeWidth={2} />
        <span className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-100/95">
          Primary ranked file · deterministic anchor
        </span>
      </div>
      <div className="px-4 py-4 font-mono text-[15px] leading-relaxed sm:text-base sm:leading-relaxed">
        <code className="text-slate-500">
          {dir.length > 0 ? (
            <>
              {dir.map((seg, i) => (
                <span key={i}>
                  {i > 0 ? <span className="text-slate-600">/</span> : null}
                  <span className="text-slate-400">{seg}</span>
                </span>
              ))}
              <span className="text-slate-600">/</span>
            </>
          ) : null}
          <span className="text-lg font-semibold text-emerald-200 sm:text-xl">
            {file}
          </span>
          {lineRange ? (
            <span className="text-base font-medium text-sky-400/95">{lineRange}</span>
          ) : null}
        </code>
      </div>
    </div>
  );
}

function CandidateWhyStrip({ rca }: { rca: RcaResult }) {
  const ev = rca.evidenceRef?.trim();
  const hasEv = Boolean(ev && ev !== "—");
  const path = rca.rootCausePath?.trim();
  const shortPath =
    path && path.length > 96 ? `${path.slice(0, 94)}…` : path;

  return (
    <div className="rounded-xl border border-sky-500/20 bg-sky-500/[0.05] px-4 py-3.5 ring-1 ring-inset ring-sky-500/10">
      <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-400/90">
        Why this candidate
      </p>
      <p className="mt-1 text-xs text-slate-500">
        Top pick from deterministic ranking — not from the assistive layer.
      </p>
      <div className="mt-3 grid gap-2.5 sm:grid-cols-3">
        <div className="rounded-lg border border-white/[0.06] bg-black/[0.88] px-3 py-2.5">
          <div className="flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wide text-slate-500">
            <Hash className="h-3 w-3 text-emerald-500/80" strokeWidth={2.5} />
            Ranking
          </div>
          <p className="mt-1 font-mono text-sm font-semibold tabular-nums text-emerald-300/95">
            {rca.rank > 0 ? `#${rca.rank}` : "—"}
          </p>
        </div>
        <div className="min-w-0 rounded-lg border border-emerald-500/15 bg-emerald-500/[0.06] px-3 py-2.5">
          <div className="flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wide text-emerald-400/80">
            <FileCode2 className="h-3 w-3 shrink-0" strokeWidth={2.25} />
            File path
          </div>
          <p
            className="mt-1 font-mono text-[11px] leading-snug text-emerald-100/90 break-all"
            title={path || undefined}
          >
            {shortPath ? shortPath : (
              <span className="text-slate-500">No path in response</span>
            )}
          </p>
        </div>
        <div className="min-w-0 rounded-lg border border-sky-500/20 bg-sky-500/[0.05] px-3 py-2.5">
          <div className="flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wide text-sky-400/85">
            <Link2 className="h-3 w-3 shrink-0" strokeWidth={2.25} />
            Evidence ref
          </div>
          <p
            className="mt-1 font-mono text-[11px] leading-relaxed text-sky-100/90 break-all sm:text-xs"
            title={hasEv ? ev! : undefined}
          >
            {hasEv ? ev! : (
              <span className="text-slate-500">Not linked</span>
            )}
          </p>
        </div>
      </div>
    </div>
  );
}

export function RcaResultCard({
  rca,
  className,
  showHeading = true,
}: RcaResultCardProps) {
  return (
    <div
      className={cn(
        "relative overflow-hidden rounded-2xl border-2 border-violet-500/40 bg-gradient-to-br from-violet-500/[0.18] via-[#0a0f1c] to-black/[0.96] p-6 sm:p-8",
        "shadow-[0_0_0_1px_rgba(139,92,246,0.25),0_20px_64px_-24px_rgba(0,0,0,0.65),0_0_100px_-30px_rgba(139,92,246,0.35)]",
        "ring-1 ring-inset ring-white/[0.07]",
        className
      )}
    >
      <div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-500/15 blur-3xl" />
      <div className="pointer-events-none absolute -bottom-16 -left-16 h-48 w-48 rounded-full bg-sky-500/10 blur-3xl" />
      <div className="relative">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-start gap-4">
            <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-violet-500/30 ring-1 ring-violet-400/45 shadow-[0_0_32px_-8px_rgba(139,92,246,0.5)]">
              <ShieldCheck className="h-7 w-7 text-violet-200" strokeWidth={1.75} />
            </div>
            <div className="min-w-0">
              {showHeading ? (
                <>
                  <LayerLabelPills
                    primary="Deterministic Root Cause"
                    secondary="Source of Truth"
                  />
                  <h3 className="mt-3 text-xl font-bold tracking-tight text-white sm:text-2xl">
                    Primary ranked output
                  </h3>
                  <p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-500">
                    From traces, metrics, and code correlation — auditable and
                    replayable. The assistive layer never overrides this binding.
                  </p>
                </>
              ) : (
                <div className="space-y-2">
                  <LayerLabelPills
                    primary="Deterministic Root Cause"
                    secondary="Source of Truth"
                  />
                  <p className="text-xs leading-relaxed text-slate-500">
                    Ranked anchor from the evidence store — the assistive narrative does
                    not override this path or its score.
                  </p>
                </div>
              )}
            </div>
          </div>
          <div className="flex flex-wrap items-start justify-end gap-2">
            {rca.candidateStatus ? (
              <div className="rounded-xl border border-sky-500/30 bg-sky-500/[0.1] px-3 py-2 text-center shadow-inner">
                <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-400/95">
                  Candidate
                </p>
                <p className="mt-0.5 font-mono text-xs font-semibold text-sky-200">
                  {rca.candidateStatus}
                </p>
              </div>
            ) : null}
            {rca.rank > 0 ? (
              <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/[0.12] px-4 py-2 text-center shadow-inner">
                <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-400/95">
                  Rank
                </p>
                <p className="font-mono text-2xl font-bold tabular-nums leading-tight text-emerald-300">
                  #{rca.rank}
                </p>
              </div>
            ) : null}
          </div>
        </div>

        <div className="mt-8">
          <p className="mb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-emerald-400/90">
            Root cause location
          </p>
          <p className="mb-3 text-xs leading-relaxed text-slate-500">
            This path is the deterministic binding — read assistive text only as commentary.
          </p>
          <RootCausePathBlock path={rca.rootCausePath} />
        </div>

        <div className="mt-8">
          <CandidateWhyStrip rca={rca} />
        </div>

        <div className="mt-8">
          <p className="mb-3 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">
            Evidence store references
          </p>
          <p className="mb-3 text-xs text-slate-500">
            Full ids for audit — evidence ref is the graph link for this rank.
          </p>
          <EvidenceMetadataRow
            fileId={rca.fileId}
            evidenceRef={rca.evidenceRef}
            runId={rca.runId}
          />
        </div>

        <div className="mt-8 space-y-3">
          <ConfidenceProgressBar value={rca.confidence} variant="hero" />
          {rca.confidence <= 0 ? (
            <p className="rounded-xl border border-amber-500/25 bg-amber-500/[0.06] px-4 py-3 text-sm leading-relaxed text-amber-100/90">
              <span className="font-semibold text-amber-200/95">
                {interpretConfidence(rca.confidence).label} (0%).
              </span>{" "}
              The ranked path still applies; graph signals may strengthen as correlation
              completes.
            </p>
          ) : null}
        </div>
      </div>
    </div>
  );
}
